### ISSUE TITLE
Randomly ignores files sometimes.

### ISSUE THREAD

**Issue by Jakobud** [gulp-community/gulp-concat#54]
I posted this issue on SO. Take a look here:

http://stackoverflow.com/questions/24977822/gulp-watch-concat-sometimes-ignores-some-js-files

Essentially, sometimes the concat randomly ignores files and doesn't concat them even though I wasn't even editing them.  It gets added back in if I open it and resave it.

How can I debug this to figure out why its doing this?

**Comment by chestermjr** [comment]
Still having this issue.

**Comment by contra** [comment]
If you are having a problem please provide code, not just "I am having this issue" otherwise we can't help you
